/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Menubar: typeof import('primevue/menubar')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheMenubar: typeof import('./src/components/TheMenubar.vue')['default']
  }
}
