name: "Setup tooling"
description: "This action manages installation of all required tooling and pnpm dependencies, it supports caching"
inputs:
  node-version:
    description: "NodeJS version to use"
    required: true
    default: "lts/*"
  pnpm-version:
    description: "PNPM version to use"
    required: true
    default: "latest"
  use-chrome:
    description: "Whether to install Chrome (for PDF generation) or not"
    required: true
    default: "false"
  chrome-version:
    description: "Chrome version to use (only when use-chrome is true)"
    required: true
    default: "stable"
outputs:
  chrome-version:
    description: "Chrome version installed"
    value: ${{ steps.setup-chrome.outputs.chrome-version }}
  chrome-path:
    description: "Path to chrome binary"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install pnpm dependencies
      shell: bash
      run: pnpm install
    - name: Setup chrome
      id: setup-chrome
      if: ${{ inputs.use-chrome == 'true' }}
      uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
      with:
        chrome-version: ${{ inputs.chrome-version }}
