name: "Setup tooling"
description: "This action manages installation of all required tooling and bun dependencies, it supports caching"
inputs:
  node-version:
    description: "NodeJS version to use"
    required: true
    default: "lts/*"
  bun-version:
    description: "Bun version to use"
    required: true
    default: "latest"
  use-chrome:
    description: "Whether to install Chrome (for PDF generation) or not"
    required: true
    default: "false"
  chrome-version:
    description: "Chrome version to use (only when use-chrome is true)"
    required: true
    default: "stable"
outputs:
  chrome-version:
    description: "Chrome version installed"
    value: ${{ steps.setup-chrome.outputs.chrome-version }}
  chrome-path:
    description: "Path to chrome binary"
    value: ${{ steps.setup-chrome.outputs.chrome-path }}
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Set bun cache directory
      shell: bash
      run: echo "STORE_PATH=~/.bun/install/cache" >> $GITHUB_ENV
    - name: Setup bun cache
      uses: "actions/cache@v4"
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-store-
    - name: Install bun dependencies
      shell: bash
      run: bun install
    - name: Setup chrome
      id: setup-chrome
      if: ${{ inputs.use-chrome == 'true' }}
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ inputs.chrome-version }}
