name: "Build and Deploy"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  workflow_dispatch:
    inputs:
      theme:
        type: string
        description: "Theme to use for building website and/or PDF document (jsonresume-theme-<theme>)"
        required: true
        default: macchiato-plus
      deploy:
        type: boolean
        description: "Whether to deploy or not"
        required: true
        default: false
      node-version:
        type: string
        description: "NodeJS version to use"
        required: false
        default: "lts/*"
      pnpm-version:
        type: string
        description: "PNPM version to use"
        required: false
        default: "9"
      chrome-version:
        type: string
        description: "Chrome version to use"
        required: false
        default: "stable"
env:
  artifact-key: deployment-${{ github.sha }}
  deployment-directory: dist
  full-theme-name: jsonresume-theme-${{ inputs.theme }}
  content-package-path: packages/cv-content
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup tooling
        id: setup-tooling
        uses: ./.github/actions/setup-tooling
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
          use-chrome: "true"
          chrome-version: ${{ inputs.chrome-version }}
      - name: Install selected theme
        working-directory: ${{ env.content-package-path }}
        run: pnpm install -D ${{ env.full-theme-name }}
      - name: Build website
        env:
          THEME: ${{ env.full-theme-name }}
          PUPPETEER_BROWSER_REVISION: ${{ steps.setup-tooling.outputs.chrome-version }}
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-tooling.outputs.chrome-path }}
        run: pnpm run build
      - name: Create deployable artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.artifact-key }}
          path: ${{ env.deployment-directory }}
  deploy:
    needs: build
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.artifact-key }}
