name: "Validate resume"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      node-version:
        type: string
        description: "NodeJS version to use"
        required: false
        default: "lts/*"
      bun-version:
        type: string
        description: "Bun version to use"
        required: false
        default: "latest"
env:
  NODE_VERSION: ${{ inputs.node-version || 'lts/*' }}
  BUN_VERSION: ${{ inputs.bun-version || 'latest' }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup tooling
        uses: ./.github/actions/setup-tooling
        with:
          node-version: ${{ env.NODE_VERSION }}
          bun-version: ${{ env.BUN_VERSION }}
      - name: Validate resume
        run: bun run validate
