name: "Validate resume"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      node-version:
        type: string
        description: "NodeJS version to use"
        required: false
        default: "lts/*"
      pnpm-version:
        type: string
        description: "PNPM version to use"
        required: false
        default: "9"
env:
  NODE_VERSION: ${{ inputs.node-version || 'lts/*' }}
  PNPM_VERSION: ${{ inputs.pnpm-version || '9' }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup tooling
        uses: ./.github/actions/setup-tooling
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: Validate resume
        run: pnpm run validate
